import $ from "jquery";

export const elements = {
    bodyTag: $('body'),
    desktopHeader: $('.desktop-header'),
    copyright: $('.info_copyright'),
    showPasswordBtn: $('.show-password'),
    passInput: $('#defaultForm-pass'),
    loginBtn: $('.btn-default'),
    wishList: $('.btn_heart'),
    addBtn: $('.btn_add'),
    likeBtn: $('.btn_like'),
    buyNowBtn: $('.btn_buy-now'),
    likeInd: $('.like_indicator'),
    cartInd: $('.cart_indicator'),
    loadMore: $('.btn_load-more'),
    productList: $('.product-list'),
    smallImg: $('.details-preview_small'),
    largeImg: $('.details-preview'),
    moreLessBtns: $('.numOf'),
    addToCart: $('.btn_add-to-cart'),
    numProducts: $('.quantity'),
    productDetailsPar: $('.product-details-p'),
    readMoreBtn: $('.btn_read-more'),
    collapseContent: $('.js-collapseContent'),
    collapseContentBtn: $('.js-collapseContentBtn'),
    hideCategBtn: $('.btn_hide-categories'),
    categories: $('.categories-container'),
    collapsedBtn: $('.collapsed-title'),
    collapsedArrow: $('.collapsed-arrow'),
    burgerBtn: $('.burger'),
    burgerMenu: $('.burger-menu'),
    navMobile: $('.mobile-nav'),
    cookiesModal: $('#myModal55'),
    closeModalBtn: $('.close55'),
    acceptCookiesBtn: $('.accept-cookies'),
    PRODUCT_MODULE: $('.js-productModule'),
    LOAD_MORE_MODULE: $('.js-loadMoreModule'),
    CATEGORIES_MODULE: $('.js-categoriesModule'),
    COLLAPSE_CONTENT_MODULE: $('.js-collapseContentModule')
};